
## Calculate ideal point marginal effects {.unnumbered}


### Description

This function allows you to calculate ideal point marginal effects for a
given person-level hierarchical covariate.



### Usage

<pre><code class='language-R'>## S4 method for signature 'idealstan'
id_me(
  object,
  covariate = NULL,
  pred_outcome = NULL,
  eps = 1e-04,
  draws = 100,
  cores = 1,
  lb = 0.05,
  upb = 0.95
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted <code>idealstan</code> model
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="covariate">covariate</code></td>
<td>
The character value for a covariate passed to the
'id_make' function before model fitting. Only one covariate can be processed
at a time.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="pred_outcome">pred_outcome</code></td>
<td>
Numeric value for level of outcome to predict for ordinal responses.
Defaults to top level.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="eps">eps</code></td>
<td>
The value used for numerical differentiation. Default is 1e-4. Usually 
does not need to be changed.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="draws">draws</code></td>
<td>
The total number of draws to use when calculating the marginal effects.
Defaults to 100. Use option &quot;all&quot; to use all available MCMC draws.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="cores">cores</code></td>
<td>
The total number of cores to use when calculating the marginal effects.
Defaults to 1.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="lb">lb</code></td>
<td>
The quantile for the lower bound of the aggregated effects (default is 0.05)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="upb">upb</code></td>
<td>
The quantile for the upper bound of the aggregated effects (default is 0.95)
</td></tr>
</table>


### Details

This function will calculate item-level ideal point marginal effects
for a given covariate that was passed to the 'id_make' function using the
'person_cov' option. The function will iterate over all items in the model
and use numerical differentiation to calculate responses in the scale of the
outcome for each item. Note: if the covariate is binary (i.e., only has two values),
then the function will calculate the difference between these two values instead of
using numerical differentation.



### Value

A list with two objects, <code>ideal_effects</code> with one estimate of the 
marginal effect per item and posterior draw and <code>sum_ideal_effects</code> with 
one row per item with that item's median ideal point marginal effect with the quantiles
defined by the <code>upb</code> and <code>lb</code> parameters.


