
## Generate Impulse Response Functions for Covariates {.unnumbered}


### Description

This function will generate an impulse response function (IRF)
for a given covariate. The IRF shows the marginal impact of a 1-unit
change in the covariate on a person's ideal point over time. To use 
this function, the <code>vary_ideal_pts</code> option in 
<code>id_estimate</code> must have received the <code>'AR1'</code> option
as IRFs are only available for the AR(1) auto-regressive model.



### Usage

<pre><code class='language-R'>id_plot_irf(
  object,
  cov_name = NULL,
  label_high = "Liberal",
  label_low = "Conservative",
  pred_outcome = NULL,
  recalc_vals = F,
  include = NULL,
  time_calc = 10,
  time_label = "Time Points",
  line_type = 2,
  line_width = 1,
  line_alpha = 1,
  line_color = "red",
  ci_color = "black",
  ci_alpha = 0.5,
  use_ci = TRUE,
  high_quantile = 0.95,
  low_quantile = 0.05,
  calc_varying = T
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted <code>idealstan</code> object
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="cov_name">cov_name</code></td>
<td>
The name of the covariate to plot. Leave blank to select 
from a list of available covariates
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="label_high">label_high</code></td>
<td>
The character label for the upper end of the latent scale
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="label_low">label_low</code></td>
<td>
The character label for the lower end of the latent scale
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="pred_outcome">pred_outcome</code></td>
<td>
For discrete models with more than 2 categories, 
or binary models with missing data, which outcome to predict. This should 
be a character value that matches what the outcome was coded as in the data
passed to <code>id_make</code>.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="recalc_vals">recalc_vals</code></td>
<td>
Whether to combine two variables into one through addition before
computing IRFs. If <code>TRUE</code>, two names of parameters should be passed to 
<code>cov_name</code> or selected from the dialog list
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="include">include</code></td>
<td>
A list of character names of person or group IDs for which to
calculate IRFs
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="time_calc">time_calc</code></td>
<td>
The maximum number of time points over which to calculate the
IRF
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="time_label">time_label</code></td>
<td>
Character string specifying the type of time points (default is just
<code>"Time Points"</code>)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="line_type">line_type</code></td>
<td>
The line type of the IRF line (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="line_width">line_width</code></td>
<td>
The line width of the IRF line (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="line_alpha">line_alpha</code></td>
<td>
The line alpha (transparency) of the IRF line (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="line_color">line_color</code></td>
<td>
The color of the IRF line (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="ci_color">ci_color</code></td>
<td>
The color of the IRF credible interval (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="ci_alpha">ci_alpha</code></td>
<td>
The alpha of the IRF credible interval (see <code>ggplot2</code> documentation)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="use_ci">use_ci</code></td>
<td>
Whether or not to plot a credible interval around the lines
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="high_quantile">high_quantile</code></td>
<td>
The upper limit of the posterior density to use for 
calculating credible intervals
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="low_quantile">low_quantile</code></td>
<td>
The lower limit of the posterior density to use for
calculating credible intervals
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="calc_varying">calc_varying</code></td>
<td>
if <code>TRUE</code>, will calculate marginal effects of the
covariates on each end of the latent scale (see vignette for more information)
</td></tr>
</table>


### Value

a <code>ggplot2</code> object that can be further customized if necessary


