## Function to plot dynamic ideal point models {.unnumbered}


### Description

This function can be used on a fitted <code>idealstan</code> object to plot the relative positions and 
uncertainties of legislator/persons and bills/items when the legislator/person ideal points
are allowed to vary over time.



### Usage

<pre><code class='language-R'>id_plot_legis_dyn(
  object,
  return_data = FALSE,
  include = NULL,
  item_plot = NULL,
  text_size_label = 2,
  text_size_group = 2.5,
  high_limit = 0.95,
  low_limit = 0.05,
  line_size = 1,
  highlight = NULL,
  plot_text = TRUE,
  use_ci = TRUE,
  plot_lines = 0,
  draw_line_alpha = 0.5,
  person_line_alpha = 0.3,
  person_ci_alpha = 0.8,
  item_plot_type = "non-inflated",
  show_true = FALSE,
  group_color = TRUE,
  hpd_limit = 10,
  sample_persons = NULL,
  plot_sim = FALSE,
  use_chain = NULL,
  add_cov = TRUE,
  ...
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted <code>idealstan</code> object or a named list of <code>idealstan</code>
objects if the plot is supposed to show a comparison of different fitted <code>idealstan</code>
models (see Time Series vignette)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="return_data">return_data</code></td>
<td>
If true, the calculated legislator/bill data is returned along with the plot in a list
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="include">include</code></td>
<td>
Specify a list of person/legislator IDs to include in the plot (all others excluded)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="item_plot">item_plot</code></td>
<td>
The value of the item/bill for which to plot its midpoint (character value)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="text_size_label">text_size_label</code></td>
<td>
ggplot2 text size for legislator labels
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="text_size_group">text_size_group</code></td>
<td>
ggplot2 text size for group text used for points
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="high_limit">high_limit</code></td>
<td>
A number between 0 and 1 showing the upper limit to compute the 
posterior uncertainty interval (defaults to 0.95).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="low_limit">low_limit</code></td>
<td>
A number between 0 and 1 showing the lower limit to compute the 
posterior uncertainty interval (defaults to 0.05).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="line_size">line_size</code></td>
<td>
Sets the size of the line of the time-varying ideal points.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="highlight">highlight</code></td>
<td>
A character referring to one of the persons in <code>person_labels</code> that the plot can highlight relative to other persons
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="plot_text">plot_text</code></td>
<td>
If <code>TRUE</code>, will plot <code>person_labels</code> over the lines.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="use_ci">use_ci</code></td>
<td>
Whether or not high-posterior density intervals (credible intervals) should be
plotted over the estimates (turn off if the plot is too busy)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="plot_lines">plot_lines</code></td>
<td>
The number of lines of actual draws of time-varying ideal points
to draw on the plot. Note that these are grouped by persons. Specific draws selected at random
from total number of draws of the estimation. Default is 0.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="draw_line_alpha">draw_line_alpha</code></td>
<td>
The opacity of lines plotted over the distribution (should be 
between 0 and 1, default is 0.5).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="person_line_alpha">person_line_alpha</code></td>
<td>
The transparency level of the time-varying ideal point line
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="person_ci_alpha">person_ci_alpha</code></td>
<td>
The transparency level of ribbon confidence interval around the time-varying ideal points
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="item_plot_type">item_plot_type</code></td>
<td>
Whether to show the <code>'non-inflated'</code> item/bill midpoints, 
the <code>'inflated'</code> item/bill midpoints, or produce plots for <code>'both'</code> kinds of models. 
Defaults to <code>'non-inflated'</code> and will only display an item/bill midpoint if one has been 
specified in <code>item_plot</code>.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="show_true">show_true</code></td>
<td>
Whether to show the true values of the legislators (if model has been simulated)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="group_color">group_color</code></td>
<td>
If <code>TRUE</code>, use the groups instead of individuals to plot colours
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="hpd_limit">hpd_limit</code></td>
<td>
The greatest absolute difference in high-posterior density interval shown for any point. Useful for excluding imprecisely estimated persons/legislators from the plot. Leave NULL if you don't want to exclude any.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="sample_persons">sample_persons</code></td>
<td>
If you don't want to use the full number of persons/legislators from the model, enter a proportion (between 0 and 1) to select
only a fraction of the persons/legislators.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="plot_sim">plot_sim</code></td>
<td>
Whether to plot the true values of parameters if a simulation was used to generate data 
(see <code>id_sim_gen</code>)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="add_cov">add_cov</code></td>
<td>
Whether to add values of hierarchical person-level covariates to the
time trends (defaults to TRUE).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
Other options passed on to plotting function, currently ignored
</td></tr>
</table>


### Details

This plot shows the distribution of ideal points for the legislators/persons in the model,
and also traces the path of these ideal points over time. It will plot them as a vertical
line with associated high-density posterior interval (10% to 90%). In addition, if the column index for a 
bill/item from the response matrix is passed to the <code>item_plot</code> option, then an item/bill midpoint will be overlain
on the ideal point plot, showing the point at which legislators/persons are indifferent to voting/answering on the 
bill/item. Note that because this is an ideal point model, it is not possible to tell from the midpoint itself
which side will be voting which way. For that reason, the legislators/persons are colored by their votes/scores to
make it clear.



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(idealstan)



# First create data and run a model

to_idealstan <-   id_make(score_data = senate114,
outcome = 'cast_code',
person_id = 'bioname',
item_id = 'rollnumber',
group_id= 'party_code',
time_id='date',
high_val='Yes',
low_val='No',
miss_val='Absent')

sen_est <- id_estimate(senate_data,
model_type = 2,
use_vb = TRUE,
vary_ideal_pts='random_walk',
fixtype='vb_partial',
restrict_ind_high = "BARRASSO, John A.",
restrict_ind_low = "WARREN, Elizabeth")

# After running the model, we can plot 
# the results of the person/legislator ideal points

id_plot_legis_dyn(sen_est)



```
