
## Marginal Effects Plot for Hierarchical Covariates {.unnumbered}


### Description

This function will calculate marginal effects, or the first derivative
of the IRT/ideal point model with respect to the hierarchical covariate,
separately for the two poles of the latent variable. These two marginal
effects permit the interpretation of the effect of the covariate on 
with respect to either end of the latent variable.



### Usage

<pre><code class='language-R'>id_plot_cov(
  object,
  calc_param = NULL,
  label_high = "High",
  label_low = "Low",
  cov_type = "person_cov",
  plot_model_id = NULL,
  pred_outcome = NULL,
  high_quantile = 0.95,
  low_quantile = 0.05,
  new_cov_names = NULL,
  ...
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted <code>idealstan</code> object
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="calc_param">calc_param</code></td>
<td>
Whether to calculate ideal point marginal effects for
a given covariate. If NULL, the default, the function will instead produce
a plot of the raw coefficients from the ideal point model. If passing the
name of a covariate, should be a character value of a column in the data 
passed to the
<code>id_make</code> function.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="label_high">label_high</code></td>
<td>
What label to use on the plot for the high end of the 
latent scale
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="label_low">label_low</code></td>
<td>
What label to use on the plot for the low end of the 
latent scale
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="cov_type">cov_type</code></td>
<td>
Either <code>'person_cov'</code> for person or group-level hierarchical parameters,
<code>'discrim_reg_cov'</code> for bill/item discrimination parameters from regular (non-inflated) model, and 
<code>'discrim_infl_cov'</code> for bill/item discrimination parameters from inflated model.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="plot_model_id">plot_model_id</code></td>
<td>
The integer of the model ID to plot. If NULL and there
are multiple model types, <code>facet_wrap</code> will be used to produce multiple
plots with one for each model type.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="pred_outcome">pred_outcome</code></td>
<td>
For discrete models with more than 2 categories, 
or binary models with missing data, which outcome to predict. This should 
be the value that matches what the outcome was coded as in the data
passed to <code>id_make</code>.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="high_quantile">high_quantile</code></td>
<td>
The upper limit of the posterior density to use for 
calculating credible intervals
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="low_quantile">low_quantile</code></td>
<td>
The lower limit of the posterior density to use for
calculating credible intervals
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="new_cov_names">new_cov_names</code></td>
<td>
A character vector of length equal to the number
of covariates (plus 1 for the intercept) to change the default labels.
To see the default labels, use the plot function with this option blank.
The character vector should be of th form used by
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
Additional argument passed on to <code>id_me</code>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="filter_cov">filter_cov</code></td>
<td>
A character vector of coefficients from covariate plots to exclude from
plotting (should be the names of coefficients as they appear in the plots)
</td></tr>
</table>


### Details

Because the marginal effects are always with respect to a given
outcome/response, the outcome to be predicted must be specified 
in <code>pred_outcome</code>. If it is not specified, the function
will prompt you to select one of the outcome's values in the data.

The ends of the latent variable can be specified via the 
<code>label_low</code> and <code>label_high</code> options, which will use those
labels in the ensuing plot.

To exclude parameters from the plot, use the <code>filter_cov</code> option. 
Note that the parameters must be specified using the underlying model 
syntax (however they are labeled in the plot). You can also change
the names of parameters using the <code>new_cov_names</code> option.

Note that the function produces a <code>ggplot2</code> object, which can 
be further modified with <code>ggplot2</code> functions.



### Value

A <code>ggplot2</code> plot that can be further customized with <code>ggplot2</code> functions if need be.


