
## Plot Posterior Predictive Distribution for <code>idealstan</code> Objects {.unnumbered}


### Description

This function is the actual method for generating posterior distributions 
from a fitted <code>idealstan</code> model.



### Usage

<pre><code class='language-R'>## S4 method for signature 'idealstan'
id_plot_ppc(
  object,
  ppc_pred = NULL,
  group = NULL,
  item = NULL,
  combine_item = TRUE,
  type = NULL,
  which_mod = NULL,
  prompt_plot = TRUE,
  observed_only = FALSE,
  ...
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted idealstan object
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="ppc_pred">ppc_pred</code></td>
<td>
The output of the <code>id_post_pred</code> function on a fitted idealstan object
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="group">group</code></td>
<td>
A character vector of the person or group IDs 
over which to subset the predictive distribution
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="item">item</code></td>
<td>
A character vector of the item IDs
over which to subset the predictive distribution
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="combine_item">combine_item</code></td>
<td>
Whether to combine all items together (TRUE) or create one plot for each item (FALSE)
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="type">type</code></td>
<td>
Whether to plot &quot;continuous&quot; or &quot;discrete&quot; responses
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="which_mod">which_mod</code></td>
<td>
If you are producing one plot aggregating data across multiple items and 
you have different item distributions,
then you need to specify the item type number to plot (see function documentation in
<code>id_estimate</code>).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="prompt_plot">prompt_plot</code></td>
<td>
Whether to expect a user prompt for each plot if multiple plots 
are produced (defaults to TRUE)
If NULL (default), will use the type specified in the data. 
However, if both continuous and discrete items are present, will
throw an error if NULL.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="observed_only">observed_only</code></td>
<td>
If the outcome is discrete and has missing data inflation, 
set to TRUE to only see the observed responses in the plot or FALSE to see all of the
responses (missing data category will be the largest).
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
Other arguments passed on to <code>ppc_bars</code>
</td></tr>
</table>


### Details

This function is a wrapper around <code>ppc_bars</code>,
<code>ppc_dens_overlay</code> and 
<code>ppc_violin_grouped</code> that plots the posterior predictive distribution
derived from <code>id_post_pred</code> against the original data. 
Because <code>idealstan</code> allows for different distributions for each item,
this function can either produce one predictive distribution for all items 
(the default) or it can produce one distribution for each item 
(set <code>combine_item</code> to <code>FALSE</code>). The latter is helpful if you have mixed 
distributions between items, such as continuous and dichotomous values. 
You can also subset the 
posterior predictions over
legislators/persons or
bills/item sby specifying the ID of each in the original data as a character vector. 
Only persons or items can be specified,
not both.

If you specify a value for <code>group</code> that is either a person ID or a group ID 
(depending on whether a person or group-level model was fit), then you can see the 
posterior distributions for those specific persons. Similarly, if an item ID is passed
to <code>item</code>, you can see how well the model predictions compare to the true values
for that specific item.


