
## Plot Posterior Predictive Distribution for <code>idealstan</code> Objects {.unnumbered}


### Description

This function is the generic method for generating posterior distributions 
from a fitted <code>idealstan</code> model. Functions are documented in the 
actual method.



### Usage

<pre><code class='language-R'>id_plot_ppc(object, ...)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
A fitted <code>idealstan</code> object
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
Other arguments passed on to <code>ppc_bars</code>
</td></tr>
</table>


### Details

This function is a wrapper around <code>ppc_bars</code>,
<code>ppc_dens_overlay</code> and 
<code>ppc_violin_grouped</code> that plots the posterior predictive distribution
derived from <code>id_post_pred</code> against the original data. You can also subset the 
posterior predictions over
legislators/persons or
bills/item sby specifying the ID of each in the original data as a character vector. 
Only persons or items can be specified,
not both.

If you specify a value for <code>group</code> that is either a person ID or a group ID 
(depending on whether a person or group-level model was fit), then you can see the 
posterior distributions for those specific persons. Similarly, if an item ID is passed
to <code>item</code>, you can see how well the model predictions compare to the true values
for that specific item.


