
## <code>idealstan</code> package {.unnumbered}


### Description

R Interface to Stan for Item-Response Theory Ideal Point Models



### Details

See the README on
<a href="https://github.com/saudiwin/idealstan/blob/master/README.md">GitHub</a>



### Author(s)

<strong>Maintainer</strong>: Robert Kubinec <a href="mailto:rmk7@nyu.edu">rmk7@nyu.edu</a>

Other contributors:


<ul>
<li> Jonah Gabry [contributor]

</li>
<li> Ben Goodrich [contributor]

</li>
<li> Trustees of Columbia University [copyright holder]

</li></ul>



### References


<ol>
<li> Kubinec, Robert. Generalized Ideal Point Models for Time-Varying and Missing-Data Inference. Working Paper.

</li>
<li> Clinton, J., Jackman, S., &amp; Rivers, D. (2004). The Statistical Analysis of Roll Call Data. <em>The American Political Science Review</em>, 98(2), 355-370. doi:10.1017/S0003055404001194

</li>
<li> Bafumi, J., Gelman, A., Park, D., &amp; Kaplan, N. (2005). Practical Issues in Implementing and Understanding Bayesian Ideal Point Estimation. <em>Political Analysis</em>, 13(2), 171-187. doi:10.1093/pan/mpi010

</li></ol>



### See Also

Useful links:


<ul>
<li> Report bugs at <a href="https://github.com/saudiwin/idealstan/issues">https://github.com/saudiwin/idealstan/issues</a>

</li></ul>


