#' Create data to run IRT model
#' 
#' To run an IRT model using \code{idealstan}, you must first process your data using the \code{id_make} function. 
#' 
#' @param vote_data Your legislator-bill (person-item) matrix in which legislators (persons) are in rows and 
#'    bills (items) are in columns. The cells of the matrix should contain consecutive integers \eqn{1,...K} for 
#'    ordinal \eqn{K} outcomes or integers \eqn{[0,1]} for a binary outcome in which 0 equals no (or incorrect) and 
#'    1 equals yes (or correct). If absences are included, they should be coded as the highest category \eqn{K+1} for
#'    ordinal outcomes and 2 for binary outcomes.
#'  @param simul_data Optionally, data that has been generated by the \code{\link{id_sim}} function.
#'  @param legis_cov A matrix of legislator covariates for hierarchical modeling. If multiple time points are used, then should be a 
#'  multi-column matrix with one column for each time point.
#'  @param bill_cov_reg A one-column matrix of bill covariates for hierarchical modeling of bill discrimination parameters in the non-inflated model
#'  @param bill_cov_abs A one-column matrix of bill covariates for hierarchical modeling of bill discrimination parameters in the inflated model
#'  @param legis_data An optional data frame of information about the legislators (persons). Should include a \code{legis.names} column containing names of
#'  legislators (persons) and optionally a \code{bloc} column with names of parties/blocs in the legislature
#'  @param bill_data An optional data frame of bill/item labels and other information. Should include \code{bill.names} column 
#'  containing bill labels; other columns are optioanl.
#'  @param abs_vote The value (numeric or character) that indicate absences in the data. If there are multiple possible values, 
#'  pass along a numeric or character vector of all such values.
#'  @param yes_vote The value (numeric or character) that indicate yes/correct responses in the data.
#'  If there are multiple possible values, 
#'  pass along a numeric or character vector of all such values.
#'  @param no_vote The value (numeric or character) that indicate no/incorrect responses in the data.
#'  If there are multiple possible values, 
#'  pass along a numeric or character vector of all such values.
#'  @param abst_vote The value (numeric or character) that indicate abstentions (a middle ordinal category) in the data. 
#'  If there are multiple possible values, 
#'  pass along a numeric or character vector of all such values.
#'  @param ordinal Whether or not the data contain ordinal responses. If \code{TRUE}, abstentions are used as a middle category in constructing the outcome.
#'  Otherwise the response is assumed to be binary (yes/no) or (correct/incorrect).
#'  @param time An optional integer vector of length equal to the number of columns in the response matrix (i.e., the number of bills or items)
#'  that indicates for each bill/item which time point that bill/item belongs to. This time vector is only used for models in which legislator/person
#'  ideal points are allowed to vary over time. 
#'  @param exclude_level A vector of any values that should be treated as \code{NA} in the response matrix
#'  @param inflate If \code{TRUE}, the response matrix is set up to enable modeling of absences as an inflation model in \code{\link{id_estimate}}
#'  @param simulation If \code{TRUE}, simulated values are saved in the \code{idealdata} object for later plotting with the \code{\link{id_plot_sim}} function
#' @return A \code{\link{idealdata}} object that can then be used in the \code{\link{id_estimate}} function to fit a model.
#' @export
#' @import rstan
#' @import dplyr
#' @importFrom tidyr gather spread
#' @import bayesplot
#' @import rstantools
#' @import Rcpp
#' @import methods
#' @useDynLib idealstan, .registration = TRUE
id_make <- function(vote_data=NULL,simul_data=NULL,
                           legis_cov=NULL,bill_cov_reg=NULL,
                           bill_cov_abs=NULL,
                           legis_data=NULL,bill_data=NULL,
                           abs_vote=NA,yes_vote=3L,no_vote=1L,abst_vote=2L,
                           ordinal=TRUE,time=NULL,
                           exclude_level=NULL,inflate=TRUE,simulation=FALSE) {

  if(ordinal==TRUE & inflate==TRUE) {
    votes <- c(no_vote,abst_vote,yes_vote,abs_vote)
    vote_int <- as.integer(factor(votes,levels=votes))
    names(vote_int) <- votes
    vote_labels <-  c('No','Abstain','Yes','Absent')
    abs_vote <- vote_int[length(vote_int)]
  } else if(ordinal==FALSE & inflate==TRUE) {
    votes <- c(no_vote,yes_vote,abs_vote)
    vote_int <- as.integer(factor(votes,levels=votes))
    names(vote_int) <- votes
    vote_labels <-  c('No','Yes','Absent')
    abs_vote <- vote_int[length(vote_int)]
  } else if(ordinal==TRUE & inflate==FALSE)  {
    votes <- c(no_vote,abst_vote,yes_vote)
    vote_int <- as.integer(factor(votes,levels=votes))
    names(vote_int) <- votes
    vote_labels <-  c('No','Abstain','Yes')
    abs_vote <- NA
  } else {
    votes <- c(no_vote,yes_vote)
    vote_int <- as.integer(factor(votes,levels=votes))
    names(vote_int) <- votes
    vote_labels <-  c('No','Yes')
    abs_vote <- NA
  }
  
  if(class(vote_data)=='matrix') {
    
    
    # Register all possible votes as integers, then before running the model we can change them if need be.
    cleaned <- vote_data %>% as_data_frame %>% mutate_all(funs(factor(.,levels=votes))) %>% mutate_all(funs(as.integer(.))) %>% as.matrix
  } else if(class(vote_data)=='rollcall') {
    
  } else {
    stop('Please provide either a matrix or a rollcall object as the vote_data argument.')
  }
  if(!is.null(time)) {
    if(length(time)!=nrow(cleaned)) {
      stop('Time vector must be same length as the number of columns in the vote matrix.')
    }
    time <- as.numeric(factor(time))
    max_t <- max(time)
  } else {
    time <- rep(1,ncol(cleaned))
  }
  colnames(cleaned) <- as.character(1:ncol(cleaned))
  #before doing this, need to ensure that 1) all legislators in legis_data have votes and 
  #2) the rows were correctly ordered to match vote_data <-> legis_data
  if(!is.null(legis_cov)) {
    if('data.frame' %in% class(legis_cov)) {
      legis_cov <- as.matrix(legis_cov)
      
    } else if('matrix' %in% class(legis_cov)) {
      legis_cov <- array(legis_cov,dim(c(ncol(legis_cov),nrow(legis_cov),max_t)))
    }

  } else {
    legis_cov <- array(c(rep(1,nrow(legis_data)),1,1),dim=c(1,nrow(legis_data),1))
  }
  
  if(!is.null(bill_cov_reg)) {
    if(nrow(bill_cov)!=ncol(cleaned)) {
      stop('Bill covariate data must be same length as the number of columns of vote matrix.')
    }
  } else {
    bill_cov_reg <- matrix(rep(1,ncol(cleaned)),nrow=ncol(cleaned),ncol=1)
  }
  if(!is.null(bill_cov_abs)) {
    if(nrow(bill_cov_abs)!=ncol(cleaned)) {
      stop('Bill covariate data must be same length as the number of columns of vote matrix.')
    }
  } else {
    bill_cov_abs <- matrix(rep(1,ncol(cleaned)),nrow=ncol(cleaned),ncol=1)
  }
  
  legis_data$legis.names <- row.names(vote_data)
  
  row.names(cleaned) <- as.character(1:nrow(cleaned))

  outobj <- new('idealdata',
      vote_matrix=cleaned,
      legis_data=legis_data,
      legis_cov=legis_cov,
      time=time,
      bill_cov_reg=bill_cov_reg,
      bill_cov_abs=bill_cov_abs,
      vote_labels=vote_labels,
      vote_int=vote_int,
      vote_count=length(votes) - length(exclude_level),
      abs_vote=abs_vote)
  
  if(simulation==TRUE) {
    outobj@simul_data <- simul_data
    outobj@simulation <- simulation
  }
  return(outobj)
}

#' Estimate an \code{idealstan} model
#' 
#' This function will take a pre-processed \code{\link[=id_make]{idealdata}} vote/score matrix and run one of the available IRT models on the data using
#' Stan's MCMC engine.
#' 
#' To run an IRT ideal point model, you must first pre-process your data using the \code{\link{id_make}} function. Be sure to specify the correct options for the
#' kind of model you are going to run: if you want to run an ordinal and/or an inflated model, the data needs to be processed differently.
#' As of this version of \code{idealstan}, the following model types are available:
#' \enumerate{
#'   \item IRT 2-PL (binary response) ideal point model, no absence inflation
#'   \item IRT 2-PL model (binary response) with absence inflation
#'   \item Ordinal IRT (rating scale) model incorporating abstentions as middle category, no absence inflation
#'   \item Ordinal IRT (rating scale) model incorporating abstentions as middle category with absence inflation
#' }
#' Additional models are available but have not yet been tested. You can find them by searching the included stan files for more info.
#' @section Identification
#' Identifying IRT models is challenging, and ideal point models are still more challenging because the discrimination parameters are not constrained.
#' As a result, more care must be taken to obtain estimates that are the same regardless of starting values. 
#' The parameter \code{fixtype} enables you to change the type of identification used. The default, 'vb', does not require any further
#' information from you in order for the model to be fit. In this version of identification, an unidentified model is run using
#' variational Bayesian inference (see \code{\link[rstan]{vb}}). If \code{restrict_type} is set to 'constrain_oneway', then the \code{nfix}
#' highest legislators/persons (if \code{restrict_params} is 'legis') or bills/items (if \code{restrict_params} equals 'bills') 
#' are used to constrain and identify the model. If \code{restrict_type} is set to 'constrain_twoway', then \code{nfix} highest and lowest legislators/persons
#' or bills/items are used to constrain and identify the model.
#' In addition, if \code{fixtype='vb'} is used, \code{auto_id} can be set to \code{TRUE}. This will run additional varitional Bayesian models
#' using the identification achieved and will see if the signs of the estimated parameters are at least 90 percent in the same direction. If so, 
#' the model is considered identified. If not, the function will re-run and will increase \code{nfix} by one to see if that will identify the model, 
#' ad infinitum.
#' If \code{fixtype} is set to 'constrained', then identification is achieved by constraining a specified list of legislators/persons or
#' bills/items. If \code{restrict_type} is 'constrain_oneway', then the indices of all constrained legislators/persons or bills/items
#' should be included as the row or column indices of these parameters in the response matrix as a vector in \code{restrict_ind_high}.
#' If \code{restrict_type} is 'constrain_twoway,' then the indices of high constrained parameters should go in 
#' \code{restrict_ind_high} and the indices of low constrained parameters in \code{restrict_ind_low}. The numbers of high and low
#' constrained parameters should be equal. To pick the parameter to constrain, set \code{restrict_params} to 'legis' for legislators/persons,
#' 'discrim_abs' for absence-inflated bill discrimination parameters, and 'discrim_reg' for non-inflated bill discrimination parameters.
#' If \code{fixtype} is set to 'pinned', then identification is achieved via pinning with very tight priors a set of legislators/persons or bills/items.
#' The indices of legislators/persons (i.e. row indices in the response matrix) or bills/items (column indices in the response matrix) should be passed as a vector
#' to \code{restrict_ind_high}, while \code{restrict_ind_low} should be left blank. The particular values to pin these parameters is passed as a 
#' numeric vector to \code{pin_vals}.
#' @param model_type An integer reflecting the kind of model to be estimated. See above.
#' @param use_subset Whether a subset of the legislators/persons should be used instead of the full response matrix
#' @param sample_it Whether or not to use a random subsample of the response matrix. Useful for testing.
#' @param subset_party If legislative/person data was included in the \code{\link{id_make}} function, then you can subset by
#' any value in the \code{$bloc} column of that data if \code{use_subset} is \code{TRUE}.
#' @param subset_legis A list of character values of names of legislators/persons to use to subset if \code{use_subset} is 
#' \code{TRUE} and legislative/person data was included in the \code{\link{id_make}} function with the required \code{$legis.names}
#' column
#' @param sample_size If \code{sample_it} is \code{TRUE}, this value reflects how many legislators/persons will be sampled from
#' the response matrix
#' @param nchains The number of chains to use in Stan's sampler. Minimum is one. See \code{\link[rstan]{stan}} for more info.
#' @param niters The number of iterations to run Stan's sampler. Shouldn't be set much lower than 500. See \code{\link[rstan]{stan}} for more info.
#' @param use_vb Whether or not to use Stan's variational Bayesian inference engine instead of full Bayesian inference. Pros: it's much faster.
#' Cons: it's not quite as accurate. See \code{\link[rstan]{vb}} for more info.
#' @param warmup The number of iterations to use to calibrate Stan's sampler on a given model. Shouldn't be less than 100. 
#' See \code{\link[rstan]{stan}} for more info.
#' @param ncores The number of cores in your computer to use for parallel processing in the Stan engine. 
#' See \code{\link[rstan]{stan}} for more info.
#' @param fixtype Sets the particular kind of identification used on the model, could be one of 'vb','constrained' or 'pinned'.
#'  See details for more information.
#' @param restrict_type Determines whether constraints will only be set on one direction 'constrain_oneway' or both high/low
#' constrains 'constrain_twoway'. Ignored if \code{fixtype} is equal to 'pinned'.
#' @param restrict_params Determines which parameters in the model are used for identification. If \code{fixtype} is 'vb', can be
#' either 'legis' (legislators/persons) or 'bills' (discrimination parameters for bills/items). Otherwise, the value must be one
#' of the available classes of parameters: 'legis' for persons/legislators, 'discrim_abs' for the absence-inflated bill discrimination
#' parameters, or 'discrim_reg' for the non-inflated bill discrimination parameters.
#' @param auto_id If \code{TRUE}, a variational Bayesian version of your model will be run using \code{\link[rstan]{vb}} in a 
#' non-identified form. Depending on what is set via \code{restrict_type} and \code{restrict_params}, bills/items or 
#' persons/legislators will be used to constrain and identify the model. 
#' @param auto_id If \code{fixtype} is set to "vb", the identification function will be re-run 
#' with multiple \code{\link[rstan]{vb}} models until the different model estimates show underlying identification. Not perfect, but
#' works pretty well.
#' @param pin_vals If \code{fixtype} is set to 'pinned', then a vector of numeric values of which to pin the legislators/persons or 
#' bills/items should be given.
#' @param restrict_ind_high If \code{fixtype} is not "vb", the particular indices of legislators/persons or bills/items to constrain high
#' @param restrict_ind_low If \code{fixtype} is not "vb", the particular indices of legislators/persons or bills/items to constrain low. 
#' (Note: not used if values are pinned).
#' @param discrim_reg_sd Set the prior standard deviation of the bimodal prior for the discrimination parameters for the non-inflated model.
#' @param discrim_abs_sd Set the prior standard deviation of the bimodal prior for the discrimination parameters for the inflated model.
#' @param legis_sd Set the prior standard deviation for the legislators (persons) parameters
#' @param diff_reg_sd Set the prior standard deviation for the bill (item) intercepts for the non-inflated model.
#' @param diff_abs_sd Set the prior standard deviation for the bill (item) intercepts for the inflated model.
#' @param restrict_sd Set the prior standard deviation for constrained parameters
#' @param ... Additional parameters passed on to Stan's sampling engine. See \code{\link[rstan]{stan}} for more information.
#' @return A fitted \code{\link{idealstan}} object that contains posterior samples of all parameters either via full Bayesian infererence
#' or a variational approximation if \code{use_vb} is set to \code{TRUE}. This object can then be passed to the plotting functions for further analysis.
#' @seealso \code{\link{id_make}} for pre-processing data,
#' \code{\link{id_plot}} for plotting results,
#' \code{\link{summary}} for obtaining posterior quantiles,
#' \code{\link{posterior_predict}} for producing predictive replications.
#' @export
id_estimate <- function(idealdata=NULL,model_type=2,use_subset=FALSE,sample_it=FALSE,
                           subset_party=NULL,subset_legis=NULL,sample_size=20,
                           nchains=4,niters=2000,use_vb=FALSE,nfix=1,restrict_params='legis',
                           pin_vals=NULL,restrict_ind_high=NULL,
                           restrict_ind_low=NULL,
                           restrict_type='constrain_oneway',
                           fixtype='vb',warmup=floor(niters/2),ncores=4,
                           auto_id=FALSE,
                           discrim_reg_sd=1,
                           discrim_abs_sd=1,
                           legis_sd=1,
                           diff_reg_sd=5,
                           diff_abs_sd=1,
                           restrict_sd=1,
                           ...) {
  
  
  if(use_subset==TRUE || sample_it==TRUE) {
    idealdata <- subset_ideal(idealdata,use_subset=use_subset,sample_it=sample_it,subset_party=subset_party,
                              subset_legis=subset_legis,sample_size=sample_size)
  }
  

    hier_type <- suppressWarnings(.get_hier_type(idealdata))
    idealdata@stanmodel <- stanmodels[['irt_standard']]
   
    #Using an un-identified model with variational inference, find those parameters that would be most useful for
    #constraining/pinning to have an identified model for full Bayesian inference
  
  num_legis <- nrow(idealdata@vote_matrix)
  num_bills <- ncol(idealdata@vote_matrix)
  legispoints <- rep(1:num_legis,times=num_bills)
  billpoints <- rep(1:num_bills,each=num_legis)
  timepoints <- idealdata@time[billpoints]
  avg_particip <- rep(1,num_legis)
  Y <- c(idealdata@vote_matrix)

  #Remove NA values, which should have been coded correctly in the make_idealdata function
  
    remove_nas <- !is.na(Y)
    Y <- Y[remove_nas]
    legispoints <- legispoints[remove_nas]
    billpoints <- billpoints[remove_nas]
    timepoints <- timepoints[remove_nas]

  this_data <- list(N=length(Y),
                    T=max(idealdata@time),
                    Y=Y,
                    hier_type=hier_type,
                    num_legis=num_legis,
                    num_bills=num_bills,
                    ll=legispoints,
                    bb=billpoints,
                    time=timepoints,
                    LX=dim(idealdata@legis_cov)[1],
                    SRX=ncol(idealdata@bill_cov_reg),
                    SAX=ncol(idealdata@bill_cov_abs),
                    legis_pred=idealdata@legis_cov,
                    srx_pred=idealdata@bill_cov_reg,
                    sax_pred=idealdata@bill_cov_abs,
                    particip=avg_particip,
                    model_type=model_type,
                    discrim_reg_sd=discrim_reg_sd,
                    discrim_abs_sd=discrim_abs_sd,
                    legis_sd=legis_sd,
                    diff_reg_sd=diff_reg_sd,
                    diff_abs_sd=diff_abs_sd,
                    restrict_sd=restrict_sd)
  
  idealdata <- id_model(object=idealdata,fixtype=fixtype,model_type=model_type,this_data=this_data,
                        nfix=nfix,restrict_params=restrict_params,restrict_ind_high=restrict_ind_high,
                        restrict_ind_low=restrict_ind_low,
                        restrict_type=restrict_type,
                        auto_id=auto_id,
                        ncores=ncores)

  # Now remake the data to reflect the constrained parameters
 
  num_legis <- nrow(idealdata@vote_matrix)
  num_bills <- ncol(idealdata@vote_matrix)
  legispoints <- rep(1:num_legis,times=num_bills)
  billpoints <- rep(1:num_bills,each=num_legis)
  timepoints <- idealdata@time[billpoints]

    
  #   apply(idealdata@vote_matrix,1,function(x) {
  #     if(model_type %in% c(2,4,6)) {
  #       count_abs <- sum(x==idealdata@abs_vote,na.rm=TRUE)
  #       
  #     } else {
  #       count_abs <- sum(is.na(x))
  #     }
  #     particip_rate <- 1 - (count_abs/length(x))
  #     return(particip_rate)
  #   }) 
  # avg_particip <- scale(avg_particip)[,1]
  Y <- c(idealdata@vote_matrix)
  
  #Remove NA values, which should have been coded correctly in the make_idealdata function
  
  remove_nas <- !is.na(Y)
  Y <- Y[remove_nas]
  legispoints <- legispoints[remove_nas]
  billpoints <- billpoints[remove_nas]
  timepoints <- timepoints[remove_nas]

  pin_vals <- if(any(is.null(pin_vals))) {
    rep(1,idealdata@restrict_num_high)
  } else {
    pin_vals
  }
  dim(pin_vals) <- idealdata@restrict_num_high
  this_data <- list(N=length(Y),
                    T=max(idealdata@time),
                    Y=Y,
                    hier_type=hier_type,
                    num_legis=num_legis,
                    num_bills=num_bills,
                    ll=legispoints,
                    bb=billpoints,
                    num_fix_high=idealdata@restrict_num_high,
                    num_fix_low=idealdata@restrict_num_low,
                    constrain_par=idealdata@param_fix,
                    constraint_type=idealdata@constraint_type,
                    LX=dim(idealdata@legis_cov)[1],
                    SRX=ncol(idealdata@bill_cov_reg),
                    SAX=ncol(idealdata@bill_cov_abs),
                    legis_pred=idealdata@legis_cov,
                    srx_pred=idealdata@bill_cov_reg,
                    sax_pred=idealdata@bill_cov_abs,
                    time=timepoints,
                    particip=avg_particip,
                    model_type=model_type,
                    pin_vals=pin_vals,
                    discrim_reg_sd=discrim_reg_sd,
                    discrim_abs_sd=discrim_abs_sd,
                    diff_reg_sd=diff_reg_sd,
                    diff_abs_sd=diff_abs_sd,
                    legis_sd=legis_sd,
                    restrict_sd=restrict_sd)

  outobj <- sample_model(object=idealdata,nchains=nchains,niters=niters,warmup=warmup,ncores=ncores,
                         this_data=this_data,use_vb=use_vb,...)
  
  outobj@model_type <- model_type
  
  return(outobj)
  
}
