
# define some global variables for use with dplyr
if(getRversion() >= "2.15.1")  utils::globalVariables(c('get_samples2',
                                                        'abs_data',
                                                        'abs_mid',
                                                        'bill_pos',
                                                        'group_id',
                                                        'Iteration',
                                                        'outcome',
                                                        'person_id',
                                                        'reg_data',
                                                        'reg_mid',
                                                        'time_id',
                                                        'time_point',
                                                        'true_pt',
                                                        'variables',
                                                        'item_high',
                                                        'item_low',
                                                        'item_median',
                                                        "Model",
                                                        '5%',
                                                        '95%',
                                                        ":=",
                                                        'item_type'))

